### ISSUE TITLE
#1 Initialization - Prepare Project

### ISSUE THREAD

**Issue by danielspaniol** [danielspaniol/Roguelike#1]
## Use Context
As a _developer_
I want the _project to be prepared properly_
so that _I can start writing the game in Kotlin and use OpenGL_

## Tasks:

- [x] Create Java/Kotlin project in IntelliJ with gradle
    - It should have the default folders for source-code and test-code
    - It should use the newest beta version of Kotlin

- [x] Add dependend libraries
    - Java std lib
    - Kotlin std lib
    - Slick2D
    - KotlinTest

- [x] Configure gradle plugins
    - Add a plugin to automatically copy the natives for OpenGL

- [x] Setup .gitignore file
    - ignore build folder
    - ignore local IDEA settings
    - ignore auto-generated files
    - ignore temp files

**Comment by danielspaniol** [comment]
Didn't mention temp files in the .gitignore since there were none.
This means that the ignore file must be updated later on as you encounter auto generated files.
