### ISSUE TITLE
#3 Create Scene System

### ISSUE THREAD

**Issue by danielspaniol** [danielspaniol/Roguelike#3]
## Use Context
As a _level designer_
I want _an easy an clean API_
in order to _edit the game world without having knowledge of coding_

## ToBe Solution
The basic syntax should be something like this:

    val mainMenu = scene {
        id { SceneIds.MAIN_MENU }
        music { Assets.MainMenuBackgroundMusic }
        gui {
            button {
                x { 100 }
                y { 500 }
                width { 100 }
                height { 25 }
                onClick {
                    changeScene(newScene = SceneIds.SETTINGS_MENU)
                }
            }
        }
        world {
            gameObject {
                name { "Player" }
                capsuleHitbox {
                    radius { 1.meter }
                    height { 2.meter }
                }
            }
        }
    }

## Tasks
- [x] Create subclass of BasicGameState to be instantiated by the scene-builder
- [x] Create builder function
    - ID needs to work already and needs to be mandatory
    - Other building functions like `world`, `gui` etc. do not need to be implemented yet
- [x] Create an enum to hold all scene IDs
